blacklist: []
build_space: build/gitlab_ci
catkin_make_args: []
cmake_args:
- -DHARDWARE_VERSION=ned2
- -DCATKIN_ENABLE_TESTING=ON
- -DENABLE_COVERAGE_TESTING=ON
- -DCMAKE_BUILD_TYPE=Debug
devel_layout: linked
devel_space: devel/gitlab_ci
extend_path:  /opt/ros/noetic
install: true
install_space: install/gitlab_ci
isolate_install: false
jobs_args: []
log_space: log/gitlab_ci
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
