blacklist: []
build_space: build/debug/one
catkin_make_args: []
cmake_args:
- -DHARDWARE_VERSION=one
- -DCATKIN_ENABLE_TESTING=ON
- -DENABLE_COVERAGE_TESTING=ON
- -DCMAKE_BUILD_TYPE=Debug
devel_layout: linked
devel_space: devel/debug/one
extend_path: /opt/ros/melodic
install: false
install_space: install/debug/one
isolate_install: false
jobs_args: []
log_space: logs/debug/one
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
