# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_base_to_mors_1
    - joint_base_to_mors_2
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

controller_list:
  - name: "niryo_robot_follow_joint_trajectory_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: "gazebo_tool_commander"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_base_to_mors_1
      - joint_base_to_mors_2

niryo_robot_follow_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.05
    joint_1: {trajectory: 0.5, goal: 0.2}
    joint_2: {trajectory: 0.5, goal: 0.2}
    joint_3: {trajectory: 0.5, goal: 0.2}
    joint_4: {trajectory: 0.5, goal: 0.2}
    joint_5: {trajectory: 1.0, goal: 0.3}
    joint_6: {trajectory: 1.0, goal: 0.3}
  stop_trajectory_duration: 1.0
  state_publish_rate: 20
  allow_partial_joints_goal: true # test to send partial joints, so they are not all updated for the jog joints




  action_monitor_rate: 10

gazebo_tool_commander:
  type: effort_controllers/JointTrajectoryController
  joints:
      - joint_base_to_mors_1
      - joint_base_to_mors_2
  gains:
    joint_base_to_mors_1:
      p: 100
      d: 1
      i: 1
    joint_base_to_mors_2:
      p: 100
      d: 1
      i: 1

gazebo_ros_control/pid_gains:
  joint_1: {p: 100, d: 1, i: 1, i_clamp: 1}
  joint_2: {p: 100, d: 1, i: 1, i_clamp: 1}
  joint_3: {p: 100, d: 1, i: 1, i_clamp: 1}
  joint_4: {p: 100, d: 1, i: 1, i_clamp: 1}
  joint_5: {p: 100, d: 1, i: 1, i_clamp: 1}
  joint_6: {p: 100, d: 1, i: 1, i_clamp: 1}
  joint_base_to_mors_1: {p: 100, d: 1, i: 1}
  joint_base_to_mors_2: {p: 100, d: 1, i: 1}